Repository harvester/harvester-ui-extension, pull requests merged in 2025-08, with the labels that each got.

#443 fix: featureFlags is undefined when installing lower version of ui-ext
  pkg/harvester/utils/feature-flags.js
Labels: require backport/v1.5, require backport/v1.6

#448 feat: add restore failed message in VM state description
  pkg/harvester/models/kubevirt.io.virtualmachine.js
Labels: require backport/v1.6

#454 fix: use default when csi-driver-config is not configured
  pkg/harvester/edit/harvesterhci.io.storage/CDISettings.vue
Labels: require backport/v1.6

#456 chore: bump version to v1.6.0-rc6
  package.json
  pkg/harvester/package.json
Labels: require backport/v1.6

#460 refactor: remove unneeded divider in storage class action menu
  pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
Labels: require backport/v1.6

#462 fix: spec.domain.memory.guest is lost when restart VM
  pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
  pkg/harvester/mixins/harvester-vm/index.js
Labels: require backport/v1.6

#459 fix: resource page detail title link
  pkg/harvester/config/harvester-map.js
  pkg/harvester/models/harvester.js
  pkg/harvester/models/harvester/configmap.js
  pkg/harvester/models/harvester/k8s.cni.cncf.io.networkattachmentdefinition.js
  pkg/harvester/models/harvester/logging.banzaicloud.io.clusterflow.js
  pkg/harvester/models/harvester/logging.banzaicloud.io.clusteroutput.js
  pkg/harvester/models/harvester/logging.banzaicloud.io.flow.js
  pkg/harvester/models/harvester/logging.banzaicloud.io.output.js
  pkg/harvester/models/harvester/monitoring.coreos.com.alertmanagerconfig.js
  pkg/harvester/models/harvester/secret.js
  pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
Labels: require backport/v1.6

#468 ci: add .github/release.yml
  .github/release.yml
Labels: require backport/v1.6, ci

#476 ci: correct set PR label script name
  .github/workflows/release-label.yaml
  .github/workflows/run-lint.yaml
Labels: require backport/v1.6, ci

#482 chore: bump version to v1.7.0-dev
  package.json
  pkg/harvester/package.json
Labels: chore

#483 chore: add v1.6.1 and v1.7.0 feature flags
  pkg/harvester/config/feature-flags.js
Labels: chore

#490 build: modify the check-version script
  scripts/check-version.sh
Labels: other, build
