Repository harvester/harvester-ui-extension, pull requests merged in 2025-09, with the labels that each got.

#487 fix: preserve YAML device parameters on config editing
  pkg/harvester/mixins/harvester-vm/index.js
Labels: fix

#506 ci: update renovate.json to remove semanticCommitScope
  .github/renovate.json
Labels: ci

#511 feat: display N/A in vlanID for overlay network
  pkg/harvester/models/k8s.cni.cncf.io.networkattachmentdefinition.js
Labels: feat

#520 feat: add info banner static route tab
  pkg/harvester/config/doc-links.js
  pkg/harvester/edit/kubeovn.io.vpc/StaticRoutes.vue
  pkg/harvester/l10n/en-us.yaml
Labels: feat

#529 chore: bump to 1.5.2
  package.json
Labels: chore

#535 fix: force fetch VM data after changing backup-target setting
  pkg/harvester/list/kubevirt.io.virtualmachine.vue
Labels: fix
